apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ include "pod.name" . }}
    chart: {{ include "pod.chart" . }}
    release: {{ .Values.name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pod.name" . }}
      release: {{ .Values.name }}
  template:
    metadata:   
      labels:
        app: {{ include "pod.name" . }}
        release: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.global.repoPrefix }}{{ .Values.global.repoSpace }}{{ .Values.deployment.image.repo }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        # command: 
        # - "/docker-entrypoint.sh"
        ports:
        - name: http
          containerPort: 1337
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 8Gi
          requests:
            cpu: 200m
            memory: 1Gi
        env:
        - name: REACT_APP_BACKEND_URL
          value: {{ .Values.backendUrl }}


