apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "pod.name" . }}
    chart: {{ include "pod.chart" . }}
    release: {{ .Values.name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  # - port: 13000
  #   name: controller-http
  selector:
    app: {{ include "pod.name" . }}
    release: {{ .Values.Name }}
