apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ include "pod.name" . }}
    chart: {{ include "pod.chart" . }}
    release: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pod.name" . }}
      release: {{ .Chart.Name }}
  template:
    metadata:   
      labels:
        app: {{ include "pod.name" . }}
        release: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.repoPrefix }}{{ .Values.global.repoSpace }}{{ .Values.deployment.image.repo }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        command: 
        - "yarn"
        - "prod"
        ports:
        - name: http
          containerPort: 1337
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 8Gi
          requests:
            cpu: 200m
            memory: 1Gi 

