apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-info
  namespace: {{ .Values.namespace }}
data:
  # CUSTOM_WEBHOOK_URL: "http://localhost:13000/git-commit-push"
  CUSTOM_WEBHOOK_GIT_AUTHOR: "Git-Controller"
  CUSTOM_WEBHOOK_GIT_EMAIL: "seonguk.cho@ondotsystems.com"
  CUSTOM_WEBHOOK_GIT_MESSAGE: "[Automation] Changed from Strapi Admin UI"
  CUSTOM_WEBHOOK_REPO_REMOTE: "origin"
  CUSTOM_WEBHOOK_REPO_REF: "push-test"
  CUSTOM_WEBHOOK_REPO_URL: https://github.com/arin-pang/foodadvisor.git